service:
    postgres:
        image: postgress:13
        enviroment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: n3wairfl0w 
            POSTGRES_DB: airflow 
        volumes: 
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5 
        restart: always

docker run -it \
    -e POSTGRES_USER="root" \
    -e POSTGRES_PASSWORD="root" \
    -e POSTGRES_DB="ny_taxi" \
    -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
    -p 5432:5432 \cle
    postgres:13

https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf